#!/usr/bin/env Rscript

# ==============================================================================
# Aim:
# Identify FOS-enriched ATAC peak regions by comparing FOS-TF signal against the
# matched IgG / first-antibody-negative background.
#
# Process:
#   1. Import peak-level read counts generated by bedtools multicov.
#      The input table contains ATAC peak coordinates and read counts for FOS-TF
#      and IgG/background BAM files.
#
#   2. Define peak IDs from genomic coordinates and filter out low-count peaks.
#      The minimum count threshold is adjusted by brain region.
#
#   3. Use edgeR to test whether each peak shows higher FOS-TF signal than IgG
#      background.
#
#   4. To avoid correcting away the expected global depth difference between FOS
#      and IgG libraries, force the effective library sizes to be equal instead of
#      applying standard library-size normalization.
#
#   5. Classify significantly FOS-enriched peaks based on FDR, then export enriched
#      and non-enriched peak sets as BED files.
#
# Inputs:
#   - counts_ATACvalidCells_<REGION>_TF_IgG_in_ATACpeaks_q30_rm_dups.tsv
#       Columns: chr, start, end, FOS-TF count, IgG/background count
#
# Outputs:
#   - EnrichedPeaks_edgeR_<REGION>_FOS_mergedRep_noLibNorm.bed
#       Peaks significantly enriched in FOS-TF relative to IgG/background.
#
#   - non_EnrichedPeaks_edgeR_<REGION>_FOS_mergedRep_noLibNorm.bed
#       Peaks not classified as FOS-enriched.
#
# Notes:
#   - This analysis intentionally avoids standard library-size normalization because
#     lower IgG depth is expected biologically/technically and should not be scaled
#     to match the FOS-TF library.
#   - edgeR is used here with a fixed dispersion because the comparison is performed
#     on merged TF and IgG/background count tracks rather than replicate-level counts.
#   - REGION should be set to one of: BLA, dHPC, or Cortex.
# ==============================================================================

library(dplyr)
library(edgeR)

# config -----------------------------------------------------------------------
REGION <- c("BLA", "dHPC", "Cortex")[3]
THRESHOLD_MIN <- if(REGION %in% c("BLA", "dHPC")){8}else{10}
FINAL_RES_DIR <- "path/to/your/final/dir"

# import data ------------------------------------------------------------------
dflist <- lapply(datanames, 
                 function(name){
                   
                   tmp <- read.table(paste0("counts_ATACvalidCells_", REGION, "_TF_IgG_in_ATACpeaks_q30_rm_dups.tsv"), 
                                     sep = "\t", header = F)
                   colnames(tmp) <- c("Chr", "Start", "End", "TF", "IgG")
                   tmp$Peak_ID <- paste0(tmp$Chr, ":", tmp$Start + 1, "-", tmp$End)

                   return(tmp)
                   
                 })
names(dflist) <- datanames

# define FOS-enrich peaks -----------------------------------------------------
group <- factor(c("TF","IgG"))
design <- model.matrix(~group)

bcv <- 0.3
disp <- bcv^2


tmp_df <- dflist[[1]][,c("TF","IgG")]
rownames(tmp_df) <- dflist[[1]]$Peak_ID

tmp_df <- tmp_df[which((tmp_df$TF + tmp_df$IgG) > THRESHOLD_MIN),]

y <- DGEList(counts = tmp_df)
y <- calcNormFactors(y)

y$samples$lib.size <- c(500000, 500000)

fit <- glmFit(y, design, dispersion = disp)
lrt <- glmLRT(fit)

res <- topTags(lrt, n = Inf)$table

res$Class <- case_when(res$FDR < 0.05~"Enrich",
                       TRUE~"non_Enrich")


tmp_df$PeakID <- rownames(tmp_df)
res$PeakID <- rownames(res)

# export -----------------------------------------------------------------------
Enrich_bed <- data.frame(chr = sub(":.+", "", rownames(res)[which(res$Class == "Enrich")]),
                         start = sub("-[0-9]+$", "", rownames(res)[which(res$Class == "Enrich")])%>% sub(".+:", "", .),
                         end = sub(".+-", "", rownames(res)[which(res$Class == "Enrich")]))

write.table(Enrich_bed, paste0(FINAL_RES_DIR, "/FOS_EnrichedPeaks_edgeR_", REGION, "_mergedRep_fixedLibSize_TMM.bed"), sep = "\t", quote = F, row.names = F, col.names = F)


nonEnrich_bed <- data.frame(chr = sub(":.+", "", rownames(res)[which(res$Class == "non_Enrich")]),
                            start = sub("-[0-9]+$", "", rownames(res)[which(res$Class == "non_Enrich")])%>% sub(".+:", "", .),
                            end = sub(".+-", "", rownames(res)[which(res$Class == "non_Enrich")]))

write.table(nonEnrich_bed, paste0(FINAL_RES_DIR, "FOS_non_EnrichedPeaks_edgeR_", REGION, "_mergedRep_fixedLibSize_TMM.bed"), sep = "\t", quote = F, row.names = F, col.names = F)
