#!/usr/bin/env Rscript

# ==============================================================================
# scMultiome preprocessing, clustering, and annotation pipeline
# ------------------------------------------------------------------------------
# Purpose:
#   Build a Seurat object from 10x Multiome RNA/ATAC data, perform RNA/ATAC QC,
#   run hierarchical RNA-based clustering, remove putative doublets based on
#   mixed lineage marker expression, re-call peaks in singlet cells, calculate
#   chromVAR motif deviation scores for downstream motif analysis, and assign
#   final cell-type annotations using external cluster annotation tables.
#
# Workflow:
#   1. Load 10x Multiome gene expression and ATAC peak count matrices.
#   2. Create a Seurat object with RNA and ATAC assays.
#   3. Perform RNA/ATAC quality control using region-specific thresholds.
#   4. Run first-round clustering to assign broad cell classes.
#   5. Split cells into excitatory neurons, inhibitory neurons, and glia.
#   6. Run second-round clustering within each broad cell class.
#   7. Inspect lineage marker expression and remove manually annotated doublets,
#      undetermined clusters, and "only" clusters.
#   8. Reconstruct singlet-cell Seurat objects from the QC-filtered object.
#   9. Re-run RNA normalization, peak calling, ATAC dimensional reduction, and
#      chromVAR on singlet cells.
#  10. Run third-round clustering and assign final cell-type annotations.
#
# Notes for reproducibility:
#   - Edit only the CONFIG section before running on a new machine or dataset.
#   - REGION controls region-specific QC, clustering, and annotation parameters.
#   - Parameter tables are read from external metadata files to keep manual
#     thresholds and cluster annotations explicit.
#   - For mPFC, RNA assays are split by Sample and integrated with Harmony.
#   - Putative doublets are identified manually from second-round clusters using
#     mutually incompatible lineage marker expression.
#   - Final objects are saved as a list of Seurat objects:
#       Exc_Neu, Inh_Neu, and Glia.
#
# Required external files:
#   - filtered_feature_bc_matrix.h5
#   - filtered_feature_bc_matrix/features.tsv
#   - atac_fragments.tsv.gz
#   - SeuratQCvalues_histone_MO.txt
#   - ClusteringParamter_scMultiome.txt
#   - CellTypeAnnotation_whole_nuclei_scMultiome.txt
#   - JASPAR2024.sqlite3
#
# Major outputs:
#   - SO_SeuratQC.rds
#       QC-filtered multiome object before hierarchical clustering.
#   - second_clustering_doublet_marker_FeaturePlot_*.pdf
#       Marker gene FeaturePlots used to inspect putative doublet clusters.
#   - SO_list_Annotated.rds
#       Final annotated singlet-cell Seurat object list after third clustering.
#
# Important:
#   - This pipeline assumes that the sample suffix in cell barcodes encodes
#     sample identity as 1, 2, 3, or 4.
#   - Manual annotation tables must match the cluster numbers generated by the
#     corresponding first, second, and third clustering steps.
#   - Re-running the script after changing clustering parameters may require
#     updating the annotation table.
# ==============================================================================

library(dplyr)
library(ggplot2)
library(Seurat)
library(Signac)
library(EnsDb.Mmusculus.v79)
library(TFBSTools)
library(BSgenome.Mmusculus.UCSC.mm10)
library(purrr)

# config
REGION <- c("BLA", "Hippo", "mPFC")[1]

BASE_DIR <- "/path/to/cellranger/outs"
RESULT_DIR_FINAL <- "/path/to/output/directory"

QC_PARAMETER_FILE <- "path/to/Github/1_scMultiome/1_Preprocess/metadata/SeuratQCvalues_histone_MO.txt"
CLUSTERING_PARAMETER_FILE <- "path/to/Github/1_scMultiome/1_Preprocess/metadata/ClusteringParamter_scMultiome.txt"
CELLTYPEANNOTATION_FILE <- "path/to/Github/1_scMultiome/1_Preprocess/metadata/CellTypeAnnotation_whole_nuclei_scMultiome.txt"

annotation <- GetGRangesFromEnsDb(EnsDb.Mmusculus.v79)
seqlevelsStyle(annotation) <- "UCSC"
# helper -----------------------------------------------------------------------
parse_dims <- function(x) {
  parts <- strsplit(x, ":")[[1]]
  as.integer(parts[1]):as.integer(parts[2])
}


# load data --------------------------------------------------------------------
count <- Read10X_h5(paste0(BASE_DIR, "/filtered_feature_bc_matrix.h5"))
fragpath <- paste0(BASE_DIR, "/atac_fragments.tsv.gz")

Feature_names <- read.delim(paste0(BASE_DIR, "/filtered_feature_bc_matrix/features.tsv"),
                            header = FALSE,
                            stringsAsFactors = FALSE)

# create a Seurat object using RNA counts
SO <- CreateSeuratObject(
  count = count$"Gene Expression",
  assay = "RNA",
  min.cells = 3
)

# create ATAC assay and add it to the object


SO[["ATAC"]] <- CreateChromatinAssay(
  counts = count$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)

# QC ---------------------------------------------------------------------------    
# by RNA 
DefaultAssay(SO) <- "RNA"

SO@meta.data$Sample <- case_when(sub(".+-", "", rownames(SO@meta.data)) == "1"~"HC-1",
                                 sub(".+-", "", rownames(SO@meta.data)) == "2"~"Cond4h-1",
                                 sub(".+-", "", rownames(SO@meta.data)) == "3"~"HC-2",
                                 sub(".+-", "", rownames(SO@meta.data)) == "4"~"Cond4h-2")

mt_gene <- Feature_names$V2[which(sub("mt-", "", Feature_names$V2) != Feature_names$V2)]
SO[["percent.mt"]] <- PercentageFeatureSet(SO, features = mt_gene)

# by ATAC 
DefaultAssay(SO) <- "ATAC"
SO <- NucleosomeSignal(SO)
SO <- TSSEnrichment(SO)

qc_params <- read.delim(QC_PARAMETER_FILE, stringsAsFactors = FALSE)
qc_params <- qc_params[which(qc_params$region == REGION),]
SO <- subset(
  x = SO,
  subset = percent.mt < qc_params$percent.mt &
    nFeature_RNA > qc_params$nFeature_RNA_min & 
    nFeature_RNA < qc_params$nFeature_RNA_max &
    nCount_ATAC < qc_params$nCount_ATAC_max &
    nCount_ATAC > qc_params$nCount_ATAC_min &
    TSS.enrichment > qc_params$TSS.enrichment &
    nucleosome_signal < qc_params$nucleosome_signal)

saveRDS(SO, paste0(RESULT_DIR_FINAL, "/", REGION, "_SO_SeuratQC.rds"))
# First clustering -------------------------------------------------------------
# Normalize RNA 
DefaultAssay(SO) <- "RNA"

if(REGION == "mPFC"){
  SO@assays$RNA <- split(x = SO@assays$RNA, f = SO@meta.data$Sample)
}

SO <- SCTransform(SO)
DefaultAssay(SO) <- "SCT"

SO <- RunPCA(SO, verbose = FALSE)

clustering_params <- read.delim(CLUSTERING_PARAMETER_FILE, stringsAsFactors = FALSE)
clustering_params <- clustering_params[which(clustering_params$region == REGION & clustering_params$clustering == "first"),]


if(REGION == "mPFC"){
  
  SO <- IntegrateLayers(            
    object = SO,                    
    method = HarmonyIntegration,    
    orig.reduction = "pca",         
    new.reduction = "harmony",      
    assay = "SCT"                   
  ) 
  
  SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims), reduction = "harmony")
  SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution, graph.name = "SCT_snn")
  SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims), reduction = "harmony", reduction.name = "umap_harmony")

  }else{
  
  SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims), reduction = "pca")
  SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution, graph.name = "SCT_snn")
  SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims), reduction.name = "umap_SCT")
  
  }

# Calculate ratio of marker genes and annotate clusters ------------------------
compute_marker_ratios <- function(SO, assay = "SCT", slot = "counts", eps = 1e-4) {
  stopifnot(requireNamespace("Seurat", quietly = TRUE))
  
  # markers
  markers <- list(
    GABA    = "Gad2",
    VGlut1  = "Slc17a7",
    VGlut2  = "Slc17a6",
    non_Neuro = c("Slc1a3","Mal","Mog","Pdgfra","C1qb","Sostdc1")
  )
  
  # grab counts (genes x cells)
  mat <- Seurat::GetAssayData(SO, assay = assay, slot = slot)
  
  # helper: vector of counts per cell for a gene; 0 if missing
  get_gene <- function(g) {
    if (g %in% rownames(mat)) as.numeric(mat[g, ]) else rep(0, ncol(mat))
  }
  
  # individual genes
  gad2    <- get_gene(markers$GABA)
  slc17a7 <- get_gene(markers$VGlut1)
  slc17a6 <- get_gene(markers$VGlut2)
  
  # non-neuronal sum across its marker set (per cell)
  nn_genes_present <- intersect(markers$non_Neuro, rownames(mat))
  non_neuro_sum <- if (length(nn_genes_present) > 0) {
    colSums(mat[nn_genes_present, , drop = FALSE])
  } else {
    rep(0, ncol(mat))
  }
  
  # ratios (add small eps to avoid div-by-zero & log issues)
  df <- data.frame(
    row.names = colnames(mat),
    GABA_per_VGlut1      = (gad2    + eps) / (slc17a7 + eps),
    GABA_per_VGlut2      = (gad2    + eps) / (slc17a6 + eps),
    GABA_per_non_Neuro   = (gad2    + eps) / (non_neuro_sum + eps),
    VGlut1_per_non_Neuro = (slc17a7 + eps) / (non_neuro_sum + eps),
    VGlut1_per_GABA      = (slc17a7 + eps) / (gad2 + eps),
    VGlut2_per_non_Neuro = (slc17a6 + eps) / (non_neuro_sum + eps),
    VGlut2_per_GABA      = (slc17a6 + eps) / (gad2 + eps),
    non_Neuro_per_GABA   = (non_neuro_sum + eps) / (gad2    + eps),
    non_Neuro_per_VGlut1 = (non_neuro_sum + eps) / (slc17a7 + eps),
    non_Neuro_per_VGlut2 = (non_neuro_sum + eps) / (slc17a6 + eps)
  )
  
  df$Cluster <- SO@meta.data$seurat_clusters
  
  df_summary <- df %>% group_by(., Cluster) %>% summarise_all(funs(mean))
  
  df_summary[,2:ncol(df_summary)] <- df_summary[,2:ncol(df_summary)] %>% t() %>% scale() %>% t() %>% as_tibble()
  
  df_for_plt <- df_summary %>% reshape2::melt()
  
  
  return(df_for_plt)
}

df_Ratio_Markergenes <- compute_marker_ratios(SO)
g <- ggplot(df_Ratio_Markergenes, aes(x = Cluster, y = variable, fill = value)) +
  geom_tile()

ggsave(paste0(RESULT_DIR_FINAL, "/", REGION, "_first_clustering_markers.png"), g)
  

# Annotate each cluster
annotation_params <- read.delim(CELLTYPEANNOTATION_FILE, stringsAsFactors = FALSE)
annotation_params <- annotation_params[which(annotation_params$region == REGION & annotation_params$clustering == "first"),]

cluster_to_celltype <- setNames(
  annotation_params$CellType,
  annotation_params$ClusterNumber
)

clusters <- as.character(SO@meta.data$seurat_clusters)

SO@meta.data$Annotation_first <- cluster_to_celltype[clusters]
SO@meta.data$Annotation_first <- factor(SO@meta.data$Annotation_first, levels = annotation_params$CellType)

# Separate SO into three groups
CellName_list <- lapply(c("Exc_Neu", "Inh_Neu", "Glia"), 
                        function(ct){
                          
                          levels(SO@meta.data$Annotation_first)[grep(ct, levels(SO@meta.data$Annotation_first))]
                          
                        })
names(CellName_list) <- c("Exc_Neu", "Inh_Neu", "Glia")

CellID_list <- lapply(CellName_list, 
                      function(cn){
                        
                        rownames(SO@meta.data)[which(SO@meta.data$Annotation_first %in% cn)]
                        
                      })

# filter raw seurat object using the cell ID
SO_SeuratQC <- readRDS(paste0(RESULT_DIR_FINAL, "/", REGION, "_SO_SeuratQC.rds"))

SO_SeuratQC@meta.data$CellID <- rownames(SO_SeuratQC@meta.data)
SO_list <- lapply(CellID_list, 
                  function(id){
                    
                    subset(SO_SeuratQC, subset = CellID %in% id)
                    
                  })



# Second clustering -------------------------------------------------------------
# Normalize RNA 
SO_list <- lapply(SO_list, 
                  function(SO){
                    DefaultAssay(SO) <- "RNA"
                    
                    if(REGION == "mPFC"){
                      SO@assays$RNA <- split(x = SO@assays$RNA, f = SO@meta.data$Sample)
                    }
                     
                    SO <- SCTransform(SO)
                    DefaultAssay(SO) <- "SCT"
                    
                    SO
                  })



clustering_params <- read.delim(CLUSTERING_PARAMETER_FILE, stringsAsFactors = FALSE)
clustering_params <- clustering_params[which(clustering_params$region == REGION & clustering_params$clustering == "second"),]

SO_list <- map2(SO_list, c("Exc_Neu", "Inh_Neu", "Glia"),
                  function(SO, ct){
                    
                    SO <- RunPCA(SO, verbose = FALSE)
                    
                    if(REGION == "mPFC"){
                      SO <- IntegrateLayers(
                        object = SO,
                        method = HarmonyIntegration,
                        orig.reduction = "pca",
                        new.reduction = "harmony"
                      )
                      
                      SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction = "harmony")
                      SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution[which(clustering_params$celltype == ct)], graph.name = "SCT_snn")
                      SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction.name = "umap_harmony")

                    }else{
                      
                      SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction = "pca")
                      SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution[which(clustering_params$celltype == ct)], graph.name = "SCT_snn")
                      SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction.name = "umap_SCT")
                      
                    }
                   
                    SO
                    
                  })

doublet_markers <- c(
  "Rbfox3",   # Neuron
  "Slc17a7",  # VGlut1
  "Slc17a6",  # VGlut2
  "Gad1",    # Inh
  "Gad2",    # Inh
  "Gja1",  # Astro
  "Mog",   # Oligo
  "Mal",     # Oligo
  "Pdgfra",  # OPC
  "C1qb"     # Microglia
)

MarkerGene_featureplot <- map2(SO_list, c("Exc_Neu", "Inh_Neu", "Glia"),
                                 function(SO, ct){
                                   
                                   p <- FeaturePlot(SO, features = doublet_markers)
                                   ggsave(
                                     filename = file.path(
                                       RESULT_DIR_FINAL,
                                       paste0(REGION, "_second_clustering_doublet_marker_FeaturePlot_", ct, ".pdf")
                                     ),
                                     plot = p,
                                     width = 14,
                                     height = 10
                                   )

                                 })

# Annotate each cluster
annotation_params <- read.delim(CELLTYPEANNOTATION_FILE, stringsAsFactors = FALSE)

SO_list <- map2(SO_list, c("Exc_Neu", "Inh_Neu", "Glia"),
                  function(SO, ct){
                    
                    annotation_params_selected <- annotation_params[which(annotation_params$region == REGION & 
                                                                   annotation_params$clustering == "second" &
                                                                   annotation_params$group == ct),]
                    
                    cluster_to_celltype <- setNames(
                      annotation_params_selected$CellType,
                      annotation_params_selected$ClusterNumber
                    )
                    
                    clusters <- as.character(SO@meta.data$seurat_clusters)
                    
                    SO@meta.data$Annotation_second <- cluster_to_celltype[clusters]
                    
                    SO@meta.data$Annotation_second <- factor(SO@meta.data$Annotation_second,
                                                             levels = annotation_params_selected$CellType)
                    
                    SO
                  })

CellName_list <- lapply(SO_list, 
                        function(SO){
                          
                          celltypes <- unique(SO@meta.data$Annotation_second)
                          
                          remove_pattern <- "undetermined|doublet|only"
                          
                          celltypes <- celltypes[
                            !grepl(remove_pattern, celltypes, ignore.case = TRUE)
                          ]
                          
                          celltypes
                          
                        })
names(CellName_list) <- c("Exc_Neu", "Inh_Neu", "Glia")

CellID_list <- map2(CellName_list, SO_list,
                      function(cn, SO){
                        
                        rownames(SO@meta.data)[which(SO@meta.data$Annotation_second %in% cn)]
                        
                      })

# filter raw seurat object using the cell ID
SO_SeuratQC <- readRDS(paste0(RESULT_DIR_FINAL, "/", REGION, "_SO_SeuratQC.rds"))
SO_SeuratQC@meta.data$CellID <- rownames(SO_SeuratQC@meta.data)

SO_singlet_list <- lapply(CellID_list, 
                  function(id){
                    
                    subset(SO_SeuratQC, subset = CellID %in% id)
                    
                  })


# Third clustering -------------------------------------------------------------
# Normalize RNA 
SO_singlet_list <- lapply(SO_singlet_list, 
                          function(SO){
                            DefaultAssay(SO) <- "RNA"
                            
                            if(REGION == "mPFC"){
                              SO@assays$RNA <- split(x = SO@assays$RNA, f = SO@meta.data$Sample)
                            }
                            
                            SO <- SCTransform(SO)
                            DefaultAssay(SO) <- "SCT"
                            
                            SO
                          })

# Re-perform peakcalling, perform dimension reductio
SO_singlet_list <- lapply(SO_singlet_list, 
                          function(SO){
                            DefaultAssay(SO) <- "ATAC"
                            
                            # peak call
                            peaks <- CallPeaks(SO, macs2.path = "/path/to/macs2")
                            
                            peaks <- keepStandardChromosomes(peaks, pruning.mode = "coarse")
                            peaks <- subsetByOverlaps(x = peaks, ranges = Signac::blacklist_mm10, invert = TRUE)
                            
                            # count 
                            macs2_counts <- FeatureMatrix(
                              fragments = Fragments(SO),
                              features = peaks,
                              cells = colnames(SO)
                            )
                            
                            SO[["peaks"]] <- CreateChromatinAssay(
                              counts = macs2_counts,
                              annotation = annotation,
                              fragments = Fragments(SO)
                            )
                            
                            DefaultAssay(SO) <- "peaks"
                            
                            # Normalization and linear dimensional reduction 
                            SO <- FindTopFeatures(SO, min.cutoff = 5)
                            SO <- RunTFIDF(SO)
                            SO <- RunSVD(SO)
                            
                            SO
                          })

# calculate chromVAR
pfm <- getMatrixSet(
  x = "JASPAR2024.sqlite3", # https://jaspar.elixir.no/downloads/
  opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
)

SO_singlet_list <- lapply(SO_singlet_list, 
                          function(SO){
                            
                            SO <- AddMotifs(
                              object = SO,
                              genome = BSgenome.Mmusculus.UCSC.mm10,
                              pfm = pfm
                            )
                            
                            SO <- RunChromVAR(
                              object = SO,
                              genome = BSgenome.Mmusculus.UCSC.mm10,
                              new.assay.name = "chromvar"
                            )
                            
                            SO
                          })

clustering_params <- read.delim(CLUSTERING_PARAMETER_FILE, stringsAsFactors = FALSE)
clustering_params <- clustering_params[which(clustering_params$region == REGION & clustering_params$clustering == "third"),]

SO_singlet_list <- map2(SO_singlet_list, c("Exc_Neu", "Inh_Neu", "Glia"),
                        function(SO, ct){
                          
                          DefaultAssay(SO) <- "SCT"
                          SO <- RunPCA(SO, verbose = FALSE)
                          
                          if(REGION == "mPFC"){
                            SO <- IntegrateLayers(
                              object = SO,
                              method = HarmonyIntegration,
                              orig.reduction = "pca",
                              new.reduction = "harmony"
                            )
                            
                            SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction = "harmony")
                            SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution[which(clustering_params$celltype == ct)], graph.name = "SCT_snn")
                            SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction = "harmony", reduction.name = "umap_harmony")
                            
                          }else{
                            
                            SO <- FindNeighbors(SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction = "pca")
                            SO <- FindClusters(SO, resolution = clustering_params$cluster_resolution[which(clustering_params$celltype == ct)], graph.name = "SCT_snn")
                            SO <- RunUMAP(object = SO, dims = parse_dims(clustering_params$lsi_dims[which(clustering_params$celltype == ct)]), reduction.name = "umap_SCT")
                            
                          }
                          
                          SO
                          
                        })


# Annotate each cluster
annotation_params <- read.delim(CELLTYPEANNOTATION_FILE, stringsAsFactors = FALSE)

SO_singlet_list <- map2(SO_singlet_list, c("Exc_Neu", "Inh_Neu", "Glia"),
                        function(SO, ct){
                          
                          annotation_params_selected <- annotation_params[which(annotation_params$region == REGION & 
                                                                                  annotation_params$clustering == "third" &
                                                                                  annotation_params$group == ct),]
                          
                          cluster_to_celltype <- setNames(
                            annotation_params_selected$CellType,
                            annotation_params_selected$ClusterNumber
                          )
                          
                          clusters <- as.character(SO@meta.data$seurat_clusters)
                          
                          SO@meta.data$Annotation <- cluster_to_celltype[clusters] %>% sub("_1$|_2$|_3$", "", .)
                          
                          SO@meta.data$Annotation <- factor(SO@meta.data$Annotation,
                                                            levels = annotation_params_selected$CellType %>% sub("_1$|_2$", "", .) %>% unique())
                          
                          SO@meta.data$CellID <- rownames(SO@meta.data)
                          
                          CellID_keep <- SO@meta.data$CellID[!grepl("undetermined", SO$Annotation, ignore.case = TRUE)]
                          SO <- subset(SO, CellID %in% CellID_keep)
        
                          SO
                        })

saveRDS(SO_singlet_list, paste0(RESULT_DIR_FINAL, "/", REGION, "_SO_list_Annotated.rds"))