#!/usr/bin/env Rscript

# ==============================================================================
# Cell-type marker peak detection from annotated scMultiome objects
# ------------------------------------------------------------------------------
# Purpose:
#   Load final annotated singlet-cell Seurat objects and identify marker peaks
#   for each annotated cell type within excitatory neurons, inhibitory neurons,
#   and glial cells. Differentially accessible peaks are detected using
#   Wilcoxon rank-sum tests, and the difference in detection percentage between
#   each target cell type and all remaining cells is added to the output table.
#
# Workflow:
#   1. Load the final annotated Seurat object list generated by the preprocessing
#      and annotation pipeline.
#   2. For each broad cell class object: Exc_Neu, Inh_Neu, and Glia.
#   3. For each annotated cell type within the object, run FindMarkers() to
#      identify marker peaks against all other cells.
#   4. Calculate percent_diff as pct.1 - pct.2 for each marker peak.
#   5. Save marker peak tables separately for Exc_Neu, Inh_Neu, and Glia.
#
# Notes:
#   - This script assumes that SO_list contains three Seurat objects in the order:
#       Exc_Neu, Inh_Neu, and Glia.
#   - Cell identities should already be set to the final cell-type annotation
#     before running FindMarkers().
#   - To identify marker peaks rather than RNA markers, the default assay should
#     be set to the peak assay, usually "peaks".
#
# Required input:
#   - SO_list_Annotated.rds
#       A list of final annotated Seurat objects.
#
# Major outputs:
#   - <REGION>_CellType_MarkerPeaks_Exc_Neu.rds
#   - <REGION>_CellType_MarkerPeaks_Inh_Neu.rds
#   - <REGION>_CellType_MarkerPeaks_Glia.rds
#
# ==============================================================================

library(Seurat)
library(Signac)

# config
REGION <- c("BLA", "Hippo", "mPFC")[1]

RESULT_DIR_FINAL <- "/path/to/output/directory"

# load data --------------------------------------------------------------------
SO_list <- readRDS(paste0(RESULT_DIR_FINAL, "/SO_list_Annotated.rds"))

CT_DA_Peaks_list <- lapply(SO_list, 
                           function(SO){
                             
                             DefaultAssay(SO) <- "peaks"
                             
                             Idents(SO) <- SO@meta.data$Annotation
                             
                             da_peaks_subcelltype <- lapply(levels(Idents(SO)), 
                                                         function(ct){
                                                           
                                                           FindMarkers(
                                                             object = SO,
                                                             ident.1 = ct,
                                                             test.use = 'wilcox',
                                                             min.pct = 0.1
                                                           )
                                                           
                                                         })
                             names(da_peaks_subcelltype) <- levels(Idents(SO))
                             
                             da_peaks_subcelltype <- lapply(da_peaks_subcelltype, 
                                                         function(df){
                                                           
                                                           df$percent_diff <- df$pct.1 - df$pct.2
                                                           return(df)
                                                           
                                                         })
                             da_peaks_subcelltype
                             
                           })

for(i in seq_along(CT_DA_Peaks_list)){
  
  saveRDS(CT_DA_Peaks_list[[i]],
          paste0(RESULT_DIR_FINAL, "/", REGION, "_CellType_MarkerPeaks_", c("Exc_Neu", "Inh_Neu", "Glia")[i], ".rds"))
  
}